### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by TungstenE2** [chr-fritz/fritzbox_exporter#3]
Hi all,

I am trying to install fritz_exporter using Docker on my Synology NAS in order to read my Fritzbox 7490 via Prometheus.

I am struggeling with the setup.

How exactly to provide User and Password to fritz_exporter?

Can you support and update documentation?

Thx

**Comment by chr-fritz** [comment]
Please take a look into the [Running with Docker](https://github.com/chr-fritz/fritzbox_exporter#running-with-docker) section of the readme: https://github.com/chr-fritz/fritzbox_exporter#running-with-docker

I can not provide any further documentation about running on Synology NAS as i don't have access to one.
